#!/bin/bash

pubvideo 0
pubvideo 1
pubvideo 2
pubvideo 3
pubvideo 4
pubvideo 5
pubvideo 6
pubvideo 7
pubvideo 8
pubvideo 9
pubvideo 10
pubvideo 11
pubvideo 12
pubvideo 13
pubvideo 14
pubvideo 15
pubvideo 16
pubvideo 17
pubvideo 18
pubvideo 19
pubvideo 20
pubvideo 21
pubvideo 22
pubvideo 23
